#!/bin/bash
################################################################
#
# initialize pacman db and sort mirrors to the users best speed
#
################################################################

ntpdate pool.ntp.org &
/usr/bin/pacman-mirrors --geoip -m rank
/usr/bin/pacman -Sy

